sudo: false
language: python
dist: xenial  # required for Python >= 3.7

python:
  - "3.7"

env:
  global:
    - TOXENV=py

before_install:
  - pip install --quiet "pip>=19.0"
  - pip install --quiet tox coveralls

script:
  - tox

after_success:
  - coveralls

matrix:
  include:

    # This is somehow required to run the "default" job:
    - env:
        - TOXENV=py

    - &check
      env:
        - TOXENV=style
      script:
        - tox
      after_success: skip
    - <<: *check
      env:
        - TOXENV=type

notifications:
  email: false
